eco_map/eco_map/urls.py
# coding: utf-8

from django.conf.urls import patterns, include, url
from eco_map.views import HomeView


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^point/add$', 'eco_map.views.addPointView', name="add_point"),
    # url(r'^eco_map/', include('eco_map.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

eco_map/lib/google-api-python-client/samples/django_sample/urls.py
import os
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    (r'^$', 'django_sample.plus.views.index'),
    (r'^oauth2callback', 'django_sample.plus.views.auth_return'),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    (r'^accounts/login/$', 'django.contrib.auth.views.login',
                        {'template_name': 'plus/login.html'}),

    (r'^static/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': os.path.join(os.path.dirname(__file__), 'static')
}),
)

eco_map/eco_map/forms.py
# coding: utf-8
from django import forms




class AddPointForm(forms.Form):
    name = forms.CharField(label='Название', max_length=255, required=False)
    adress = forms.CharField(label='Адрес',
                             max_length=512,
                             widget=forms.widgets.TextInput(attrs={'class':'input-xlarge'}))
    
    WASTE_TYPES = (("Paper", "Бумага"),
               ("Glass", "Стекло"),
               ("Metall", "Метал"),
               ("Plastic", "Пластик"),
               ("Danger", "Опасные отходы"),
               ("Cloth", "Одежда"),
               ("Other", "Прочее")
              )
    
    waste_types = forms.MultipleChoiceField(
                    widget=forms.widgets.CheckboxSelectMultiple(attrs={'class':'input-xlarge'}),
                    choices=WASTE_TYPES)
    work_time = forms.CharField(label='Время работы',
                                max_length=255,
                                widget=forms.widgets.TextInput(attrs={'class':'input-xlarge'}), 
                                required=False)
    phone = forms.CharField(label='Телефон', 
                            max_length=255,
                            widget=forms.widgets.TextInput(attrs={'class':'input-xlarge'}), 
                            required=False)
    comment = forms.CharField(label='Примечения',
                              widget=forms.widgets.Textarea(),
                              required=False)
    

eco_map/templates/addPointForm.html
<form class="add-point-form form-horizontal" method="post" action="{% url add_point %}">
  <fieldset>
    <div class="control-group">
      <label class="control-label" for="id_name">Название:</label>
      <div class="controls">
        {{form.name}}
        {% if form.name.errors %} 
         	<span class="help-inline">{{ form.name.errors }}</span>
        {% endif %}
      </div>
    </div>
    <div class="control-group {{form.waste_types.errors|yesno:"error,"}}">
      <label class="control-label">Принимают<span class="red">*</span>:</label>
      <div class="controls">
        {{ form.waste_types }}
        {% if form.waste_types.errors %} 
         	<span class="help-inline">{{ form.waste_types.errors }}</span>
        {% endif %}
      </div>
    </div>
    <div class="control-group {{form.adress.errors|yesno:"error,"}}">
      <label class="control-label" for="id_adress">Адрес<span class="red">*</span>:</label>
      <div class="controls">
        {{ form.adress }}
        <img style="display: block" src="https://developers.google.com/maps/documentation/places/images/powered-by-google-on-white.png">
        {% if form.adress.errors %} 
         	<span class="help-inline">{{ form.adress.errors }}</span>
        {% endif %}
      </div>
    </div>
    <a class="btn btn-large btn-info show-additional-fields" href="#">
    	<i class="icon-list-alt icon-white"></i> Показать дополнительные поля
    </a>
    <fieldset class='additional-fields hide'>
	    <div class="control-group {{form.work_time.errors|yesno:"error,"}}">
	      <label class="control-label">Время работы:</label>
	      <div class="controls">
	        {{ form.work_time }}
	        {% if form.work_time.errors %} 
	         	<span class="help-inline">{{ form.work_time.errors }}</span>
	        {% endif %}
	      </div>
	    </div>
	    <div class="control-group {{form.phone.errors|yesno:"error,"}}">
	      <label class="control-label">Телефон:</label>
	      <div class="controls">
	        {{ form.phone }}
	        {% if form.phone.errors %} 
	         	<span class="help-inline">{{ form.phone.errors }}</span>
	        {% endif %}
	      </div>
	    </div>
	    <div class="control-group {{form.comment.errors|yesno:"error,"}}">
	      <label class="control-label">Примечения:</label>
	      <div class="controls">
	        {{ form.comment }}
	        {% if form.comment.errors %} 
	         	<span class="help-inline">{{ form.comment.errors }}</span>
	        {% endif %}
	      </div>
	    </div>
	    
    </fieldset>
    
  </fieldset>
</form>

eco_map/templates/base.html
<!DOCTYPE html>
<html lang="ru" ng-app>
<head>
    <meta charset="utf-8">
    <title>Переработай это! {% block title %}{% endblock %}</title>
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->

    <!-- Le styles -->
    <link href="../static/libs/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="../static/libs/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet">
    <link href="../static/main.css" rel="stylesheet">
    
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

  <script src="../static/libs/bootstrap/js/jquery-1.7.1.min.js"></script>
  <script src="../static/libs/bootstrap/js/bootstrap.min.js"></script>
  <!-- <script src='http://docs.angularjs.org/angular-1.0.0.min.js'></script> -->
  <script type="text/javascript"
    src="http://maps.googleapis.com/maps/api/js?key=AIzaSyAntoJEkPWjK8NDAl_z_GiHdQsC6fV_OEw&sensor=true&libraries=places">
  </script>
  <script src='../static/main.js'></script> 
  
  <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-4221859-4']);
  _gaq.push(['_setDomainName', 'eco.asmon.ru']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
  
</head>
<body ng-controller="WasteListCtrl">
  <div class="container-fluid">
    <div class="row-fluid">
      <div class="span3 left-menu">
        <h2>Переработай это!</h2>
		  <div class="well choose-waste">
	        <h3>Выберите типы отходов:</h3>
	        <!-- <label ng-repeat="(key, value) in waste_types" class="checkbox">
	          <input type="checkbox" value="{{key}}">
	           {{value}}
	        </label> -->
	         
        	<label class="checkbox">
	            <input type="checkbox" value="Paper"> Бумага
	        </label>
	        <label class="checkbox">
	            <input type="checkbox" value="Glass"> Стекло
	        </label>
	        <label class="checkbox">
	            <input type="checkbox" value="Metall"> Металл
	        </label>
	        <label class="checkbox">
	            <input type="checkbox" value="Plastic"> Пластик
	        </label>
	        <label class="checkbox">
	          <input type="checkbox" value="Danger"> Опасные отходы 
	            <img rel="tooltip" title="Батарейки, аккумуляторы и т.д."
	            	 src="/static/img/icon_help_32.png" style="margin-top: -19px"> 
	        </label>
	        <label class="checkbox">
	            <input type="checkbox" value="Cloth"> Одежда
	        </label>
	        <label class="checkbox">
	            <input type="checkbox" value="Other"> Прочее
	        </label>
          </div><!--/.well -->
          
          <a class="btn btn-large btn-success" href="#addPointModal"
             data-toggle="modal">
          	<i class="icon-plus icon-white"></i> Добавить пункт
          </a>
          
          
        </div>
      <!--/ left span-->
	    
	  <div class="span9">
	  	<div id="map_canvas" style="width:100%; height: 600px"></div>
	  </div>
      <!--/ right span-->
	</div>
  </div>
	<!--/ container -->
	
	
	<!-- ==================== AddPoint modal window content	==================== -->
	<div class="modal fade hide" id="addPointModal">
	  <div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal">×</button>
	    <h2>Добавить пункт приёма</h2>
	  </div>
	  <div class="modal-body">
	  	<div class="addPointFormContainer" action="{% url add_point %}"></div>
	  	<div class="alert alert-info" style="font-size: 90%">
			Пожалуйста, как минимум, заполните поля отмеченные 
			звездочкой (<span class="red">*</span>).
		</div>
	  </div>
	  <div class="modal-footer">
	    <a href="#" class="btn btn-large" data-dismiss="modal">Отменить</a>
	    <a id="addPointButton" href="#" class="btn btn-large btn-primary">Добавить</a>
	  </div>
	</div>
	<!-- END ==================== AddPoint modal window content	==================== -->
</body>
</html>